# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02c25503278d22684b3f79ff7458951a46d173d020da78d644450e343439567cc89b2ba62785fc16c33798aa04dfcccd937332e0e86c2cbfb572502f2d975baf

test:
  secret_key_base: 418e1dd4e717e397a251fbbb9df7df046a0f996ed83596f3d9023b5dc72aca946cf0f4d09f57c4320466ee87b9ec8a3506591c88023cca3e64ca179bbd758079

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
